#!/usr/bin/env bash
# install nginx

sudo apt update
sudo apt-get -y install nginx 
cd /var/www/html || exit
sudo chmod 777 index.nginx-debian.html
echo Hello World! > index.nginx-debian.html
sudo service nginx restart
