#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt update
sudo apt-get install -y haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy_backup.cfg
echo "
frontend haproxy-main
    bind *:80
    option forwardfor
    default_backend nginx_servers
backend nginx_servers
    balance roundrobin
    server 4390-web-01  54.160.237.107:80 check
    server 4390-web-02  54.242.209.114:80 check
"| sudo tee -a /etc/haproxy/haproxy.cfg

sudo sed -i '8i ENABLED=1;' /etc/default/haproxy
sudo service haproxy restart
